# Generated by Django 3.0 on 2022-04-02 00:53

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdrf',
            options={'ordering': ['-pk'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelManagers(
            name='userdrf',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
